### ISSUE TITLE
Rename + format + duplicate error

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/monorepo#620]
1. Import data
2. Rename a column
3. Set the format of the column
4. Duplicate the dataframe
5. Get this error: 

```
Traceback (most recent call last):
  File "mito_backend.py", line 209, in receive_message
    self.handle_edit_event(event)
  File "mito_backend.py", line 145, in handle_edit_event
    'shared_variables': self.get_shared_state_variables()
  File "mito_backend.py", line 100, in get_shared_state_variables
    'analysis_data_json': self.steps_manager.analysis_data_json,
  File "steps_manager.py", line 323, in analysis_data_json
    "code": transpile(self, optimize=(is_pro() or is_running_test())),
  File "transpile.py", line 58, in transpile
    (gotten_code, code_chunk_imports) = code_chunk.get_code()
  File "set_dataframe_format_code_chunk.py", line 306, in get_code
    dataframe_format_code, _uses_numpy = get_dataframe_format_code(self.post_state, sheet_index)
  File "set_dataframe_format_code_chunk.py", line 272, in get_dataframe_format_code
    get_all_columns_format_code(state, sheet_index),
  File "set_dataframe_format_code_chunk.py", line 76, in get_all_columns_format_code
    column_header = state.column_ids.get_column_header_by_id(sheet_index, column_id)
  File "column_headers.py", line 237, in get_column_header_by_id
    return self.column_id_to_column_header[sheet_index][column_id]
KeyError: 'rename'
```

**Comment by naterush** [comment]
Great report! Will dig into this today
